# Name of website
title: novathesis LaTeX template

# Description of website
description: A LaTeX template for thesis, dissertations and similar monograph-like documents

# Your name to show in the footer
author: João M. Lourenço

# logo
logo: NOVAthesisFiles/Images/novathesis-logo-grey-white-v3.3-921x195.jpg

show_downloads: true
theme: jekyll-theme-minimal